name = "backend"
main = "src/index.ts"
compatibility_date = "2025-01-04"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYWZiZWMwZmItYjU0My00MmQ2LThhNDUtNzg0NzEyZDNlYThlIiwidGVuYW50X2lkIjoiNDRjYTRiNmY0NTFmMDdkNTk3YTk1ZWI1MWRhNmI0OWZkNTRiNjc2OTlkYmExZjg1Y2UzYTdlNTczMmJiYjgzOSIsImludGVybmFsX3NlY3JldCI6ImJmZjY0Zjk5LWQzMzAtNDViYi1hMzgwLTgzODBjMTVkYTRjNCJ9.tGKOQPM_0Y_WHPxbaD73p6Nw5InEGiwK7kmVOIq6Pk8"
JWT_SECRET="mysecretpassword"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1